"""Legacy Janus_Config.txt <-> HydraConfig conversion (CONTRACT.md §2).

Layer: ``hydrafers.config`` -- pure Python. NO pyfers/Qt import.

Two directions:
    * :func:`render_legacy_txt` -- serialize a :class:`HydraConfig` to the legacy
      text format shown in ``docs/janus_config_example.txt`` (used by
      :meth:`HydraConfig.to_legacy_txt`).
    * :func:`convert_janus_txt` -- parse a legacy ``Janus_Config.txt`` back into a
      validated :class:`HydraConfig` and optionally write it as YAML.

Legacy line grammar (per ``janus-5202`` ``cfgfile_rw.py`` / ``paramparser.c``):
    ``Name[brd][ch] value   # optional comment``
  where the ``[brd]`` and ``[ch]`` index suffixes are optional. ``Open`` always
  carries a board index (``Open[0]``). Section banners are comment lines of the
  form ``# SectionName`` and are advisory only -- params are keyed by NAME, so
  parsing does not depend on section ordering.
"""

from __future__ import annotations

import re
from pathlib import Path

from hydrafers.config.schema import (
    NUM_CHANNELS,
    AcqModeConfig,
    BoardConfig,
    DiscrConfig,
    HVBiasConfig,
    HydraConfig,
    OutputFilesConfig,
    RunCtrlConfig,
    SpectroscopyConfig,
    TestProbeConfig,
    _scalar_to_str,
)

# Width of the name column in the emitted legacy file (matches the example).
_NAME_COL = 35

# Map each global section model class to its legacy banner name. The banner
# order here is the emission order in the legacy file.
_GLOBAL_SECTIONS: tuple[tuple[str, str], ...] = (
    ("HV_bias", "hv_bias"),
    ("RunCtrl", "run_ctrl"),
    ("OutputFiles", "output_files"),
    ("AcqMode", "acq_mode"),
    ("Discr", "discr"),
    ("Spectroscopy", "spectroscopy"),
    ("Test-Probe", "test_probe"),
)

# Short per-parameter trailing comments for the emitted legacy file. Only a hint;
# the parser ignores comments entirely.
_COMMENTS: dict[str, str] = {
    "HV_Vbias": "Bias voltage (common to all channels)",
    "HV_Imax": "Max current provided by the HV.",
    "HV_Adjust_Range": "DAC range for the individual HV adjust. Options: 4.5, 2.5, DISABLED",
    "TempSensType": "Temperature Sensor Type. Options: TMP37, LM94021_G11, LM94021_G00",
    "TempFeedbackCoeff": "Temperature Feedback Coeff (mV/degC)",
    "EnableTempFeedback": "Enable Vbias Temperature Feedback",
    "AcquisitionMode": "Acquisition mode",
    "DataFilePath": "Destination folder to save the output files",
    "OF_MaxSize": "Max size of List files",
}


def _fmt_line(name: str, value: str, comment: str | None = None) -> str:
    """Format a single ``Name  value  # comment`` legacy line."""
    base = f"{name:<{_NAME_COL}}{value}"
    if comment:
        return f"{base:<{_NAME_COL + 24}}# {comment}"
    return base


def _banner(title: str) -> str:
    rule = "# " + "-" * 88
    return f"{rule}\n# {title}\n{rule}"


def render_legacy_txt(cfg: HydraConfig) -> str:
    """Render *cfg* to the legacy Janus_Config.txt text format."""
    lines: list[str] = []
    lines.append("# " + "*" * 88)
    lines.append("# params File generated by HydraFERS (hydrafers.config)")
    lines.append("# " + "*" * 88)

    # --- Connect block (per-board Open[i]) ---
    lines.append(_banner("Connect"))
    for i, board in enumerate(cfg.boards):
        lines.append(_fmt_line(f"Open[{i}]", board.Open))
    lines.append("")

    # --- Common and default settings (global params) ---
    lines.append("")
    lines.append("# " + "*" * 88)
    lines.append("# Common and Default settings")
    lines.append("# " + "*" * 88)

    for banner_name, attr in _GLOBAL_SECTIONS:
        section = getattr(cfg, attr)
        lines.append(_banner(banner_name))
        for name, value in section.__dict__.items():
            lines.append(_fmt_line(name, _scalar_to_str(value), _COMMENTS.get(name)))
        lines.append("")

    # --- Board and Channel settings (overwrite default settings) ---
    lines.append("")
    lines.append("# " + "*" * 88)
    lines.append("# Board and Channel settings (overwrite default settings)")
    lines.append("# " + "*" * 88)
    for b_idx, board in enumerate(cfg.boards):
        # board-scoped scalars (excluding Open, already in Connect block)
        for name in BoardConfig._UNIT_FIELDS:
            lines.append(_fmt_line(f"{name}[{b_idx}]", getattr(board, name)))
        for name in BoardConfig._HEX_FIELDS:
            lines.append(_fmt_line(f"{name}[{b_idx}]", "0x" + getattr(board, name)))
        lines.append(
            _fmt_line(f"TD_CoarseThreshold[{b_idx}]", str(board.TD_CoarseThreshold))
        )
        # channel-scoped arrays
        for name in BoardConfig._CHANNEL_FIELDS:
            values = getattr(board, name)
            for ch, val in enumerate(values):
                lines.append(_fmt_line(f"{name}[{b_idx}][{ch}]", str(val)))

    return "\n".join(lines) + "\n"


# Regex for a legacy parameter line: NAME with optional [brd] and [ch] suffixes,
# then whitespace, then the value (everything up to an optional trailing comment).
_LINE_RE = re.compile(
    r"^(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
    r"(?:\[(?P<brd>\d+)\])?"
    r"(?:\[(?P<ch>\d+)\])?"
    r"\s+(?P<value>.*?)\s*$"
)

# Which legacy NAMEs belong to which global section model (for routing on parse).
_GLOBAL_FIELD_OWNER: dict[str, str] = {}
for _model, _attr in (
    (HVBiasConfig, "hv_bias"),
    (RunCtrlConfig, "run_ctrl"),
    (OutputFilesConfig, "output_files"),
    (AcqModeConfig, "acq_mode"),
    (DiscrConfig, "discr"),
    (SpectroscopyConfig, "spectroscopy"),
    (TestProbeConfig, "test_probe"),
):
    for _fname in _model.model_fields:
        _GLOBAL_FIELD_OWNER[_fname] = _attr

# Legacy parameter-name aliases -> canonical schema field name. The legacy
# Janus_Config.txt (docs/janus_config_example.txt) emits ``Trg_HoldOff`` for what
# param_defs_reference.txt now calls ``Hit_HoldOff``; map it so the value is not
# silently dropped on import.
_LEGACY_NAME_ALIASES: dict[str, str] = {
    "Trg_HoldOff": "Hit_HoldOff",
}

# Board-scoped legacy NAMEs (single value, may carry a [brd] index).
_BOARD_FIELD_NAMES = frozenset(
    ("Open",)
    + BoardConfig._UNIT_FIELDS
    + BoardConfig._HEX_FIELDS
    + ("TD_CoarseThreshold",)
)
# Channel-scoped legacy NAMEs (arrays of NUM_CHANNELS).
_CHANNEL_FIELD_NAMES = frozenset(BoardConfig._CHANNEL_FIELDS)


def _strip_comment(value: str) -> str:
    """Drop a trailing ``# ...`` comment from a value token."""
    hashpos = value.find("#")
    if hashpos != -1:
        value = value[:hashpos]
    return value.strip()


def parse_legacy_txt(text: str) -> HydraConfig:
    """Parse legacy Janus_Config.txt *text* into a validated :class:`HydraConfig`."""
    # Accumulate global params and per-board param dicts; we materialise boards
    # lazily as indices appear.
    global_params: dict[str, str] = {}
    board_scalar: dict[int, dict[str, str]] = {}
    board_channel: dict[int, dict[str, list[int | None]]] = {}

    def ensure_board(idx: int) -> None:
        board_scalar.setdefault(idx, {})
        board_channel.setdefault(idx, {})

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("["):
            continue
        m = _LINE_RE.match(line)
        if not m:
            continue
        name = m.group("name")
        name = _LEGACY_NAME_ALIASES.get(name, name)
        brd = m.group("brd")
        ch = m.group("ch")
        value = _strip_comment(m.group("value"))
        if value == "":
            continue

        b_idx = int(brd) if brd is not None else 0

        if name in _CHANNEL_FIELD_NAMES:
            ensure_board(b_idx)
            arr = board_channel[b_idx].setdefault(
                name, [None] * NUM_CHANNELS
            )
            if ch is not None:
                ci = int(ch)
                if 0 <= ci < NUM_CHANNELS:
                    arr[ci] = int(value, 0)
            else:
                # no channel index -> broadcast scalar to all channels
                board_channel[b_idx][name] = [int(value, 0)] * NUM_CHANNELS
        elif name in _BOARD_FIELD_NAMES:
            ensure_board(b_idx)
            board_scalar[b_idx][name] = value
        elif name in _GLOBAL_FIELD_OWNER:
            global_params[name] = value
        # unknown names (e.g. monitor params, GUI-only tabs) are ignored

    # If no board appeared at all, create board 0 with defaults.
    if not board_scalar and not board_channel:
        ensure_board(0)

    board_indices = sorted(set(board_scalar) | set(board_channel))
    boards: list[BoardConfig] = []
    for idx in board_indices:
        kwargs: dict[str, object] = {}
        for name, val in board_scalar.get(idx, {}).items():
            kwargs[name] = val
        for name, arr in board_channel.get(idx, {}).items():
            defaults = getattr(BoardConfig(), name)
            filled = [
                defaults[i] if arr[i] is None else arr[i]
                for i in range(NUM_CHANNELS)
            ]
            kwargs[name] = filled
        boards.append(BoardConfig(**kwargs))

    # Route global params into their section sub-models.
    section_kwargs: dict[str, dict[str, str]] = {
        attr: {} for _, attr in _GLOBAL_SECTIONS
    }
    for name, val in global_params.items():
        section_kwargs[_GLOBAL_FIELD_OWNER[name]][name] = val

    return HydraConfig(
        boards=boards,
        hv_bias=HVBiasConfig(**section_kwargs["hv_bias"]),
        run_ctrl=RunCtrlConfig(**section_kwargs["run_ctrl"]),
        output_files=OutputFilesConfig(**section_kwargs["output_files"]),
        acq_mode=AcqModeConfig(**section_kwargs["acq_mode"]),
        discr=DiscrConfig(**section_kwargs["discr"]),
        spectroscopy=SpectroscopyConfig(**section_kwargs["spectroscopy"]),
        test_probe=TestProbeConfig(**section_kwargs["test_probe"]),
    )


def convert_janus_txt(
    txt_path: str | Path, yaml_path: str | Path | None = None
) -> HydraConfig:
    """Parse a legacy Janus_Config.txt and optionally save it as YAML.

    Parameters
    ----------
    txt_path:
        Path to the legacy ``Janus_Config.txt`` file.
    yaml_path:
        If given, the resulting :class:`HydraConfig` is written there as YAML.

    Returns
    -------
    HydraConfig
        The validated configuration parsed from the legacy file.
    """
    text = Path(txt_path).read_text(encoding="utf-8")
    cfg = parse_legacy_txt(text)
    if yaml_path is not None:
        # local import to avoid import cycle (loader imports nothing from here)
        from hydrafers.config.loader import save_config

        save_config(cfg, yaml_path)
    return cfg
